### ISSUE TITLE
Crash with normal use

### ISSUE THREAD

**Issue by morganrallen** [gabrielcsapo/tap-html#3]
```
/**8*/*******/*****/********/node_modules/tap-html/index.js:65
        data[plan].tests.push(data[i]);
                  ^

TypeError: Cannot read property 'tests' of undefined
```
Interestingly it passes it's own tests. I've tried matching up versions of `tape` being used and I still get this against my own tests.

**Comment by morganrallen** [comment]
OK, I figured out what's going on here, it's in a subtly different way in which we're using `tape`.

Your testing has a structure like...
```
Suite ->
  Feature Tests ->
    Test
    Test
    Test
  Feature Tests ->
    Test
```

While I'm testing in a flatter structure
```
Feature Tests ->
  Test
  Test
  Test
Feature Tests ->
  Test
```
It appears this expectation of having an addition layer is causing the issue.

**Comment by gabrielcsapo** [comment]
Can you add a sample tape file that explains this structure?

**Comment by morganrallen** [comment]
Oh yeah, forgot that.

## Not Working
```
TAP version 13
# serial connection
ok 1 got serialport
# ble
ok 2 got device discover
ok 3 device connected
ok 4 got characteristic
ok 5 subcribed
ok 6 got round-trip message

1..6
# tests 6
# pass  6

# ok
```
## Working
```
TAP version 13
# BLE Test Suite
# serial connection
ok 1 got serialport
# ble
ok 2 got device discover
ok 3 device connected
ok 4 got characteristic
ok 5 subcribed
ok 6 got round-trip message

1..6
# tests 6
# pass  6

# ok
```
The notable difference two lines containing `#`

**Comment by gabrielcsapo** [comment]
@morganrallen can you provide a test file that would generate the structure you are looking for so I can add that to a series of tests for the parser?

**Comment by gabrielcsapo** [comment]
I have a fix for this, will submit a PR, stay on the look out, just traveling today and tomorrow.
