### ISSUE TITLE
Doesn't output to stdout

### ISSUE THREAD

**Issue by morganrallen** [gabrielcsapo/tap-html#5]
When looking at `bin/tap-html` one would think this outputs to `stdout` but instead `tap-html.html` is always created. Looking at `lib/generate.js:71` it can be seen it is in fact hardcoded to `./tap-html.html`.

**Comment by gabrielcsapo** [comment]
An extra option can output the generated HTML to stdout, would that be a good addition?

**Comment by morganrallen** [comment]
My thinking is that should be the default option. Pipeline in, pipeline out. Then have an optional `-f/--file` or `-o/--out/--output/--outfile` if you want to write directly to a file.

**Comment by gabrielcsapo** [comment]
@morganrallen so my main motivation for building this was to generate an html report much like http://adamgruber.github.io/mochawesome/ for mocha. You make a good point that since these should be pipeable, it should have a default of behavior as such.

**Comment by gabrielcsapo** [comment]
Another problem with this requirement is that in order to generate the html test report, I am using webpack, in order for webpack to work it must write to disk. @morganrallen should it write to a virtual disk and only dump the contents to the physical disk if the output is wanted as such?

**Comment by morganrallen** [comment]
I've never used webpack so I don't know what the best course with that is.

**Comment by gabrielcsapo** [comment]
I think I found a solution @morganrallen
