### ISSUE TITLE
TAP input format

### ISSUE THREAD

**Issue by Frogli** [gabrielcsapo/tap-html#8]
Dear @gabrielcsapo,

Thank you for making this tool available. I have some TAP files generated by our custom unittest framework.  I want to convert these TAP files to a html report.  I did some tests with tap-html and run up a problem with the expected TAP format. If I run tap-html with my TAP files I get the error

`$ cat ../../sometests.tap | tap-html --out ./report.html`

```
/usr/local/lib/node_modules/tap-html/index.js:44
    data[currentPlan].assertions.push({
                      ^

TypeError: Cannot read property 'assertions' of undefined
    at Parser.tap.on (/usr/local/lib/node_modules/tap-html/index.js:44:23)
    at Parser.emit (events.js:182:13)
    at Parser.emit (/usr/local/lib/node_modules/tap-html/node_modules/minipass/index.js:307:25)
    at Parser.emitResult (/usr/local/lib/node_modules/tap-html/node_modules/tap-parser/index.js:554:10)
    at Parser.parseTestPoint (/usr/local/lib/node_modules/tap-html/node_modules/tap-parser/index.js:169:10)
    at Parser.parse (/usr/local/lib/node_modules/tap-html/node_modules/tap-parser/index.js:840:12)
    at Parser.write (/usr/local/lib/node_modules/tap-html/node_modules/tap-parser/index.js:343:12)
    at Stream.method [as write] (/usr/local/lib/node_modules/tap-html/node_modules/duplexer/index.js:47:39)
    at Socket.ondata (_stream_readable.js:666:20)
    at Socket.emit (events.js:182:13)
```

De tap file:
```
1..2
# Some description of a test
ok 1 Yep a test description
# Some other description of a test
ok 2 And this one is another test description
```

From from issue #3 I understand that the tool expect some description lines above the testplan (1..2). I tested this by adding two lines with only #. 

```
#
#
1..2
# Some description of a test
ok 1 Yep a test description
# Some other description of a test
ok 2 And this one is another test description
```
And indeed I do not get the error. I was wondering where can I find this in the TAP documentation or is this something tap-html specific?

Grtz

**Comment by gabrielcsapo** [comment]
@Frogli thanks for opening the issue! let me see what I can figure out from what you posted, it is probably something with the tap parser

**Comment by gabrielcsapo** [comment]
Hey @Frogli would you be able to review https://github.com/gabrielcsapo/tap-html/pull/9?

**Comment by gabrielcsapo** [comment]
Closing, if this doesn't fix the issue please reopen a new issue

**Comment by minzcmu** [comment]
Got the same err when there is no description for the specific test, e.g.

```
1..2
ok 1 Yep a test description
ok 2 And this one is another test description
```

@gabrielcsapo can we have a fix for this? thank you!

**Comment by gabrielcsapo** [comment]
Hello @minz1027 looking at making a fix for this right now

**Comment by gabrielcsapo** [comment]
@minz1027 what tool is creating this output without a description? What would the title of those two test assertions be?

**Comment by minzcmu** [comment]
We're not using tape / js to generate the tap files. 

Like for `ok 1 Yep a test description` i think the part after the number can be the title/description for that test case. 

Based on the format defined in http://testanything.org/. Comments are not required
